stages:
  download:
    cmd: python src/downloader.py
    deps:
    - src/downloader.py
    outs:
    - data/not_splitted
    
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    - data/not_splitted
    outs:
    - data/splitted

  featurize:
    cmd: python src/featurization.py
    deps:
    - data/splitted
    - src/featurization.py
    outs:
    - data/features

  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/features
    outs:
    - models
    - results/train

  inference:
    cmd: python src/inference.py
    deps:
    - src/inference.py
    - data/features
    - models
    outs:
    - results/metrics
    - results/inference

metrics:
- results/metrics
plots: 
- results/train
- results/inference

    
    
