prepare:
  split: 0.2
  seed: 42

features:
  batch_size: 32
  resize: [224, 224]
  normalize: [[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]]

train:
  num_classes: 4
  lr: 0.01
  epochs: 10

inference:
  model: "models/model.pkl"
